version: "3.4"

services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: app.dev.Dockerfile
    ports: ["3000:3000", "8000:8000"]
    environment:
      NEO4J_URI: bolt://db:7687
    command: sleep infinity
    depends_on:
      - db
    volumes:
      - .:/workspace:cached

  db:
    image: marcellodesales/neo4j-with-cypher-seed:latest
    restart: unless-stopped
    ports: [7687:7687, 7474:7474]
    environment:
      - NEO4J_AUTH=none
    volumes:
      - ./backend/tests/seed.cql:/cyphers/seed.cql
