version: "3.4"

services:
  frontend:
    restart: unless-stopped
    image: ismailmo1/famtree-webapp
    ports: ["3000:3000"]
  backend:
    restart: unless-stopped
    image: ismailmo1/famtree-api
    ports: ["8000:8000"]
    env_file: prod.env
    environment:
      NEO4J_URI: bolt://db:7687
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      REFRESH_TOKEN_EXPIRE_MINUTES: 1440
    depends_on:
      - db
  db:
    image: neo4j:latest
    restart: unless-stopped
    ports: [7687:7687, 7474:7474]
    env_file: prod.env
    volumes:
      - ./neo4j-runtime/data:/data
      - ./neo4j-runtime/logs:/logs
      - ./neo4j-runtime/import:/var/lib/neo4j/import
      - ./neo4j-runtime/plugins:/plugins
