
version: '3.4'

services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: dev.Dockerfile
    expose:
      - 3000
      - 8000
    ports: [ "3000:3000", "8000:8000" ]
    environment:
      NEO4J_URI: bolt://localhost:7687
    command: sleep infinity
    depends_on:
      - db
    volumes:
      - .:/workspace:cached

  db:
    image: neo4j
    restart: unless-stopped
    ports: [7687:7687,7474:7474]      
    environment:
      NEO4J_AUTH: none
      NEO4J_dbms_connector_https_advertised__address: "localhost:7473" 
      NEO4J_dbms_connector_http_advertised__address: "localhost:7474" 
      NEO4J_dbms_connector_bolt_advertised__address: "localhost:7687" 
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/plugins:/plugins