# This is a basic workflow to help you get started with Actions

name: Deploy frontend
env:
  IMAGE_NAME: ismailmo1/famtree-webapp
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths: 'frontend/**'
  pull_request:
    branches: [ "main" ]
    paths: 'frontend/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    update-docker-image:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          id: checkout
          
        - name: Log in to the Container registry
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PWD }}

        - name: Build and push Docker image
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: frontend
            file: frontend/frontend.prod.Dockerfile
            push: true
            tags: |
              ${{ env.IMAGE_NAME}}:${{ github.sha }}
              ${{ env.IMAGE_NAME}}:latest  
    deploy:
      needs: "update-docker-image"
      runs-on: ubuntu-latest
      steps:
      - name: restart container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          password: ${{ secrets.LINODE_PASSWORD }}
          port: ${{ secrets.LINODE_PORT }}
          script: |
            docker pull ${{ env.IMAGE_NAME }}
            wget https://raw.githubusercontent.com/ismailmo1/family-tree/main/docker-compose.prod.yml -O famtree/docker-compose.prod.yml            
            docker-compose -f famtree/docker-compose.prod.yml up -d
